# fly.toml app configuration file generated for atomic-docs on 2025-12-08T09:51:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atomic-docs'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
