import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "html",
      value: '<div class="sidebar-section-label">GETTING STARTED</div>',
      defaultStyle: false,
    },
    "getting-started/installation",
    "getting-started/first-repository",
    "getting-started/ai-agent-workflows",
    {
      type: "doc",
      id: "getting-started/atomic-vault",
      label: "Atomic Vault",
    },
    "getting-started/querying-the-graph",
    "getting-started/migrating-from-git",
    {
      type: "doc",
      id: "getting-started/git-shadow-sync",
      label: "Git Shadow",
    },
    "getting-started/train-tracks-demo",
    {
      type: "html",
      value: '<div class="sidebar-section-label">GUIDES</div>',
      defaultStyle: false,
    },
    "guides/reduce-ai-agent-rework",
    "guides/version-control-for-ai-agents",
    "guides/track-ai-agent-changes-and-reasoning",
    "guides/review-large-ai-generated-pull-request",
    "guides/audit-trail-for-ai-generated-code",
    "guides/root-cause-ai-agent-bug",
    "guides/multiple-ai-agents-without-merge-conflicts",
    {
      type: "html",
      value: '<div class="sidebar-section-label">AGENTS</div>',
      defaultStyle: false,
    },
    {
      type: "doc",
      id: "agents/overview",
      label: "How Atomic Records What Your AI Coding Agent Did",
    },
    {
      type: "doc",
      id: "agents/installing-agent-integrations",
      label: "Installing Integrations",
    },
    {
      type: "doc",
      id: "agents/provenance",
      label: "How to See Why an AI Agent Changed Your Code",
    },
    {
      type: "doc",
      id: "agents/attestations",
      label: "AI Agent Session Audit Trails: Cost, Tokens, and Model Attribution",
    },
    {
      type: "html",
      value: '<div class="sidebar-section-label">CONCEPTS</div>',
      defaultStyle: false,
    },
    {
      type: "doc",
      id: "concepts/the-lego-story",
      label: "Why Changes Compose: The Atomic Data Model",
    },
    {
      type: "doc",
      id: "concepts/graph-model-explained",
      label: "Graph Model & AI Attribution",
    },
    "concepts/change-identity",
    "concepts/hunks-edit-replacement",
    {
      type: "doc",
      id: "concepts/dual-layer-diff",
      label: "Dual-Layer Diff & Semantic Merge",
    },
    {
      type: "doc",
      id: "concepts/merging-and-conflicts",
      label: "Merging & Conflicts",
    },
    {
      type: "doc",
      id: "concepts/performance-at-scale",
      label: "Atomic Performance: Benchmarks at Agent Scale",
    },
    {
      type: "html",
      value: '<div class="sidebar-section-label">PROPOSALS</div>',
      defaultStyle: false,
    },
    "proposals/manifest-nodes",
    "proposals/virtual-working-copies",
    "proposals/performance-benchmarking-strategy",
    {
      type: "html",
      value: '<div class="sidebar-section-label">TEAMS & STORAGE</div>',
      defaultStyle: false,
    },
    {
      type: "doc",
      id: "teams/overview",
      label: "Team Collaboration",
    },
    {
      type: "html",
      value: '<div class="sidebar-section-label">COMMANDS</div>',
      defaultStyle: false,
    },
    {
      type: "doc",
      id: "commands/overview",
      label: "Overview",
    },
    {
      type: "doc",
      id: "commands/completions",
      label: "Shell Completions",
    },
    {
      type: "category",
      label: "Repository Management",
      collapsed: true,
      link: {
        type: "doc",
        id: "commands/repository-management",
      },
      items: [
        "commands/init",
        "commands/clone",
        "commands/restore",
        "commands/split",
      ],
    },
    {
      type: "category",
      label: "Working with Changes",
      collapsed: true,
      link: {
        type: "doc",
        id: "commands/working-with-changes",
      },
      items: [
        "commands/add",
        "commands/remove",
        "commands/move",
        "commands/status",
        "commands/conflicts",
        "commands/diff",
        "commands/record",
        "commands/revise",
        "commands/log",
        "commands/change",
        "commands/insert",
      ],
    },
    {
      type: "category",
      label: "Views & Tags",
      collapsed: true,
      items: ["commands/view", "commands/stash", "commands/tag"],
    },
    {
      type: "category",
      label: "Diagnostics",
      collapsed: true,
      items: ["commands/doctor"],
    },
    {
      type: "category",
      label: "Intent & Memory",
      collapsed: true,
      items: ["commands/intent", "commands/memory"],
    },
    {
      type: "category",
      label: "Remote Operations",
      collapsed: true,
      link: {
        type: "doc",
        id: "commands/remote-operations",
      },
      items: [
        "commands/org",
        "commands/workspace",
        "commands/project",
        "commands/team",
        "commands/server",
        "commands/remote",
        "commands/push",
        "commands/pull",
        "commands/clone",
      ],
    },
    {
      type: "category",
      label: "Identity",
      collapsed: true,
      items: ["commands/identity"],
    },
    {
      type: "category",
      label: "AI Agents",
      collapsed: true,
      items: ["commands/agent"],
    },
  ],
};

export default sidebars;
